---
title: "Assignment III pt. I"
author: "Dana Jensen"
date: "October 12, 2017"
output: html_document
---
---
                          "INCOMPLETE"
---
```{r setup, include=FALSE}
#prelude
knitr::opts_chunk$set(echo = TRUE)
path<-("C:/Users/Dana/Desktop/METHODS III/AssignmentVI")
setwd(path)
library(pacman, Pastecs, stats, lsr, nonlinearTseries, crqa, readr, stringr, lmerTest)
p_load(Pastecs, stats, lsr, nonlinearTseries, crqa, readr, stringr, lmerTest)
folder = file.path(path)
pitch_list<- list.files(path = folder, recursive = TRUE, pattern = "*f0.txt")
```
### Assignment 2 - Part 1 - Assessing voice in schizophrenia
Can you characterize voice in schizophrenia as acoustically different? Report the methods you used to answer this question and the results from the analyses. Add a couple of lines trying to interpret the results and a couple of lines describing limitations of the data/analyses if any is relevant.
```{r}
#NOTE TO SELF:
# Recurrance rate - how much is covered in black? (%)
# Determinisim - stability of repetitions, how likely black dot is not isolated,
# but part of a diagonal (keeps repeating)
# L - how long do shared directories go together?
# Lmax - maximum trajectory
# Entropy - when system repeats itself? How unpredictable?
# Laminarity - Verticle patterns (getting stuck)
# Trapping Time - how long you are 'trapped' in the state (verticle)

##1. In the course of this assignment you have to first select one datafile and figure out how to:

##Extract "standard" descriptors of pitch: Mean, standard deviation, range

summary.list = function(x){
  result<-c(
  Mean=mean(x$f0, na.rm=TRUE),
  Median=median(x$f0, na.rm=TRUE),
  Max.Min=range(x$f0, na.rm=TRUE),
  Range=max(x$f0, na.rm=TRUE) - min(x$f0, na.rm=TRUE),
  Variance=var(x$f0, na.rm=TRUE),
  Std.Dev=sd(x$f0, na.rm=TRUE),
  IQR=IQR(x$f0, na.rm = TRUE),
  MeanAbsDev=aad(x$f0, na.rm = TRUE),
  Coeff.Variation.Prcnt=sd(x$f0, na.rm=TRUE)/mean(x$f0, na.rm=TRUE)*100,
  Std.Error=sd(x$f0, na.rm=TRUE)/sqrt(length(x$f0[!is.na(x)])),
  Quantile=quantile(x$f0, na.rm=TRUE)
  )
return(result)
}

p = read.delim(pitch_list[1])
summary.list(p)

##Extract "complex" descriptors: recurrence quantification analysis

#par
par = list(lgM =  50, steps = seq(1, 6, 1),  radiusspan = 100,  radiussample = 40, normalize = 0,  rescale = 0,  mindiagline = 2,  minvertline = 2,  tw = 0,  whiteline = FALSE,  recpt = FALSE,  fnnpercent = 10,  typeami = 'mindip')

#optimized parameters
#~~~~~~ERROR~~~~~~~~
try(optimizeParam(p$f0, p$f0, par, min.rec = 1, max.rec = 10))

#rqa
rqa_analysis= function(x)(  
  crqa(x, x, embed = 2, delay = 1, normalize = 0, rescale = 0, radius = 0.5,
  mindiagline = 2, minvertline = 1)
)
rqa_analysis(p)

##2. Second you will have to turn the code into a function and loop through all the files (or even better use apply/sapply/lapply)
##- Remember to extract the relevant information from the file names (Participant, Diagnosis, Trial, Study)

rm(dframe)
filename = NULL
temp = NULL
id =  NULL
study = NULL
diagnosis = NULL
trial = NULL
mean= NULL
median= NULL
max.min = NULL
range = NULL
variance= NULL
std.dev= NULL
IQR= NULL
coeff.variation.prcnt= NULL
std.error= NULL
quantile= NULL
radius= NULL
delay= NULL
embed= NULL
n = 1

for (file in pitch_list){
  ##practical information
  filename[n] = file
  i = read_delim(file, delim = "\t")
  temp[n] = paste(folder, i, sep = "")
  id[n] =  str_extract(str_extract(file, "S\\d+"), "\\d+")
  study[n] = str_extract(str_extract(file,"\\S\\w{4}\\d{1}"), "\\d")
  diagnosis[n] = str_extract(str_extract(file, "D\\d"), "\\d")
  trial[n] = str_extract(str_extract(file, "T\\d+"), "\\d+")
  ##some numbers
  mean[n]= mean(i$f0)
  median[n]= median(i$f0)
  max.min[n]= range(i$f0)
  range[n]= max(i$f0) - min(i$f0)
  variance[n]= var(i$f0)
  std.dev[n]= sd(i$f0)
  IQR[n]= IQR(i$f0)
  coeff.variation.prcnt[n]= sd(i$f0)/mean(i$f0)*100
  std.error[n]= sd(i$f0)/sqrt(length(i))
  quantile[n]= quantile(i$f0)
  #~~~~~ ERROR: all NAs ~~~~
  V = try(optimizeParam(i$f0, i$f0, par, min.rec = 2, max.rec = 10))
  if (length(V)>1){
    radius[n] = V$radius
    delay[n] = V$delay
    embed[n] = V$emddim
  }else{
    radius[n] = NA
    delay[n] = NA
    embed[n] = NA
  n = n+1
}}

dframe<- data.frame(filename, id, study, diagnosis, trial, mean, median, range, variance, std.dev, IQR, coeff.variation.prcnt, std.error, quantile, radius, delay, embed)

write.csv(dframe, "schizoData.csv")

##3. Make one model per acoustic feature and test whether you can observe significant difference due to Diagnosis. Tip: Which other fixed factors should you control for (that is, include in the model)? Which random ones?

m1 = glmer(scale(range) ~ diagnosis + trial +(1|study) + (1|id), data = dframe, family = 'binomial')
summary(m1)

m2 = glmer(scale(variance) ~ diagnosis + trial + (1|study) + (1|id), data = dframe, family = 'binomial')
summary(m2)

m3 = glmer(scale(mean) ~ diagnosis + trial + (1|study) + (1|id), data = dframe, family = 'binomial')
summary(m3)

m4 = glmer(scale(std.error) ~ diagnosis + trial + (1|study) + (1|id), data = dframe, family = 'binomial')
summary(m4)

##3a. Is study a significant predictor in these models? What should you infer from this? Does study interact with diagnosis? What should you infer from this?

##Bonus points: cross-validate the model and report the betas and standard errors from all rounds to get an idea of how robust the estimates are. 

##4. Bonus Question: Compare effect size of diagnosis across the different measures. Which measure seems most sensitive?
##- Tip: to compare across measures you need to put all of them on the same scale, that is, you need to "standardize" them (z-score)

##5. Bonus question. In the Clinical Info file you have additional information about the participants. Which additional parameters (e.g. age, gender) should we control for? Report the effects.

##6. Write a paragraph reporting methods and results

## N.B. Remember to save the acoustic features of voice in a separate file, so to be able to load them next time
```
